import type { NextPage } from "next";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";

import NavBar from "../components/NavBar";
import { trpc } from "../utils/trpc";
const Guide: NextPage = () => {
  const hello = trpc.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />

      <main className="mx-auto min-h-screen max-w-7xl px-2 sm:px-6 lg:px-8">
        <h1 className="text-5xl font-extrabold leading-normal text-gray-700 md:text-[5rem]">
          Print Purchasing <span className="text-purple-300">Guide</span>
        </h1>
        <p className="text-2xl text-gray-700">
          Not sure what the difference is between PLA and Resin? We got you
          covered!
        </p>

        <h2>PLA vs Resin</h2>
        <p>
          TL;DR if you want a higher quality print, go with the resin. If you
          want a stronger print that you plan on finishing yourself, go with
          PLA.{" "}
        </p>
        <p>We currently offer two ways to print your items: PLA and Resin.</p>
        <p>
          PLA is a recyclable, natural thermoplastic material used in Fused
          Deposition Modeling (FDM) printers. These types of prints are perfect
          for cosplay, utility, or models that really don&apos;t need much
          detail. These prints come out a bit rough. We will sand and fill each
          PLA print to the best of our abilities, but you may need to finish out
          some of the imperfections we may have missed.
        </p>
        <p>
          Photopolymer resin is a light sensitive, liquid plastic used in
          stereolithography (SLA) printers. These prints are able to reach high
          quality details, thanks to the printer&apos;s 4k resolution screen.
          These prints are more or less ready to ship once they take a dunk in
          isopropyl alcohol and harden in UV light. Perfect for miniatures,
          busts, or prints that requires a lot of detail. Downside is that they
          can be more fragile than PLA. Materials also tend to be a bit more
          expensive than PLA, hence the slight up charge.
        </p>

        <h2>Available Sizes</h2>
        <p>We currently offer the following sizes: </p>
        <ul>
          <li>
            Mini: Think small enough for a table top game like Dungeons and
            Dragons or Starcraft.{" "}
          </li>
          <li>
            Small: These can range from the size of a bobble head, a mug, or
            boss level miniatures.
          </li>
          <li>
            Medium: These are your busts and statues, to small cosplay props
            like knives and accessories.
          </li>
          <li>Large: These are your multi part statues, armor pieces, etc. </li>
          <li>
            BFP: Big. F***ing. Props. These are your helmets, full armor sets,
            anything that requires a f*** ton of time to do.
          </li>
        </ul>
        <p>
          You may have noticed that these aren&apos;t exact measurements. For
          the time being, these sizes are just estimates based on the prints
          available. As we grow, we will offer more, exact measurements. Until
          then, check the print description to see roughly what size it will
          turn out.{" "}
        </p>

        <h2>Available Colors</h2>
        <p>
          Since we don&apos;t offer painting services at the moment, we try to
          offset that with different color options. They are wildly
          inconsistent. We will always have gray in stock for both types of
          materials. We also will try to have some fun and unique colors as well
          for both. If there are no colors available, that just means the model
          will be printed on whatever color we currently have.
        </p>
        <div className="flex w-full items-center justify-center pt-6 text-2xl text-blue-500">
          {hello.data ? <p>{hello.data.greeting}</p> : <p>Loading..</p>}
        </div>
        <AuthShowcase />
      </main>

      <footer className="border-t-2 py-5 text-center">
        <p className="text-sm font-medium">
          ©2022 Made with ❤️ and ☕ by Andrew Hunn
        </p>
      </footer>
    </>
  );
};

export default Guide;

const AuthShowcase: React.FC = () => {
  const { data: secretMessage } = trpc.auth.getSecretMessage.useQuery();

  const { data: sessionData } = useSession();

  return (
    <div className="flex flex-col items-center justify-center gap-2">
      {sessionData && (
        <p className="text-2xl text-blue-500">
          Logged in as {sessionData?.user?.name}
        </p>
      )}
      {secretMessage && (
        <p className="text-2xl text-blue-500">{secretMessage}</p>
      )}
      <button
        className="rounded-md border border-black bg-violet-50 px-4 py-2 text-xl shadow-lg hover:bg-violet-100"
        onClick={sessionData ? () => signOut() : () => signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
};
