import type { NextPage } from "next";

import Head from "next/head";

import Card from "../components/Cards/Card";

import CustomJob from "../components/CustomJob";
import Hero from "../components/Hero";
import NavBar from "../components/NavBar";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const { data: products } = trpc.product.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Home | DreamWalker Studios</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-zinc-900">
        <NavBar />
        <Hero />

        <div className="mx-auto  bg-zinc-800 px-2 text-white sm:px-6 lg:px-8">
          <section className="mx-auto max-w-7xl px-2 py-10 sm:px-6 lg:px-8">
            <h3 className="text-2xl font-extrabold tracking-tight sm:text-3xl ">
              Newest Arrivals
            </h3>
            <div className="mt-10 grid grid-cols-1 gap-4  p-4 md:grid-cols-2 lg:grid-cols-4">
              {products &&
                products.map((product) => (
                  <Card key={product.name} product={product} />
                ))}
            </div>
          </section>
        </div>

        {/* <section className="mx-auto my-12 max-w-7xl bg-zinc-700 px-2 sm:px-6 lg:px-8">
          <Services />
        </section> */}

        <CustomJob />
      </main>

      <footer className="border-t-2 border-zinc-700 bg-zinc-900 py-5 text-center text-white">
        <p className="text-sm font-medium">
          ©2022 Made with ❤️ and ☕ by Andrew Hunn
        </p>
      </footer>
    </>
  );
};

export default Home;

const features = [
  {
    name: "3D Files",
    description:
      "Files are acquired through open source sites, licensed through Patreon artists, or designed by hand. ",
  },
  {
    name: "Materials",
    description: "We offer two different materials, PLA and Resin. ",
  },
  {
    name: "Dimensions",
    description:
      "Each print is different. Default sizes are included in the descriptions, but adjustments can be made. (Price would be adjusted accordingly)",
  },
  {
    name: "Finish",
    description:
      "For an extra fee, we will hand sand any imperfections, fill any gaps, and prime your piece. ",
  },
  {
    name: "Shipping",
    description:
      "We are a really small operation at the moment. With that in mind, expect a wait time minimum of one month before shipping.",
  },
  {
    name: "Colors",
    description:
      "We offer a variety of colors that can change based on availability. Note that if you decide on choosing a color, your wait time will increase.",
  },
];

export function Services() {
  return (
    <div>
      <div className="mx-auto grid max-w-2xl grid-cols-1 items-center gap-y-16 gap-x-8  py-24 px-4 sm:px-6 sm:py-32 lg:max-w-7xl lg:grid-cols-2 lg:px-8">
        <div>
          <h2 className="text-3xl font-bold tracking-tight text-gray-50 sm:text-4xl">
            Print Lifecycle and Services
          </h2>
          <p className="mt-4 text-gray-300">
            Each print is hand crafted here in the USA by my soulless 3D
            printers, but I swear they are made with love! Below is what you can
            expect when ordering from me.
          </p>

          <dl className="mt-16 grid grid-cols-1 gap-x-6 gap-y-10 sm:grid-cols-2 sm:gap-y-16 lg:gap-x-8">
            {features.map((feature) => (
              <div key={feature.name} className="border-t border-gray-200 pt-4">
                <dt className="font-medium text-white">{feature.name}</dt>
                <dd className="mt-2 text-sm text-gray-400">
                  {feature.description}
                </dd>
              </div>
            ))}
          </dl>
        </div>
        <div className="grid grid-cols-2 grid-rows-2 gap-4 sm:gap-6 lg:gap-8">
          <img
            src="https://tailwindui.com/img/ecommerce-images/product-feature-03-detail-01.jpg"
            alt="Walnut card tray with white powder coated steel divider and 3 punchout holes."
            className="rounded-lg bg-gray-100"
          />
          <img
            src="https://tailwindui.com/img/ecommerce-images/product-feature-03-detail-02.jpg"
            alt="Top down view of walnut card tray with embedded magnets and card groove."
            className="rounded-lg bg-gray-100"
          />
          <img
            src="https://tailwindui.com/img/ecommerce-images/product-feature-03-detail-03.jpg"
            alt="Side of walnut card tray with card groove and recessed card area."
            className="rounded-lg bg-gray-100"
          />
          <img
            src="https://tailwindui.com/img/ecommerce-images/product-feature-03-detail-04.jpg"
            alt="Walnut card tray filled with cards and card angled in dedicated groove."
            className="rounded-lg bg-gray-100"
          />
        </div>
      </div>
    </div>
  );
}
