import type { NextPage } from "next";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";

import NavBar from "../components/NavBar";
import { trpc } from "../utils/trpc";
const Quote: NextPage = () => {
  const hello = trpc.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />

      <main className="mx-auto min-h-screen max-w-7xl px-2 sm:px-6 lg:px-8">
        <h1 className="mb-5 mt-8 text-5xl  font-bold tracking-tight text-gray-700 md:text-[5rem]">
          Request a <span className="text-blue-600">Quote</span>
        </h1>

        <p className="text-xl">
          Our offerings are trash? Want something specific? Shoot us your idea
          and we will respond to you with a quote ASAP. *Just FYI, we are not
          able to do custom models at this time. However, we are able to scour
          the internet and search for ones already completed by other artists!
          If it is not on our site, just send us the file.
        </p>
      </main>

      <footer className="border-t-2 py-5 text-center">
        <p className="text-sm font-medium">
          ©2022 Made with ❤️ and ☕ by Andrew Hunn
        </p>
      </footer>
    </>
  );
};

export default Quote;
