import { CategoryOption } from "@prisma/client";
import type { NextPage } from "next";
import {
  GetStaticPaths,
  GetStaticPropsContext,
  InferGetStaticPropsType,
} from "next";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import Card from "../../components/Cards/Card";
import { LocalProduct } from "../../components/Cards/types";
import CustomJob from "../../components/CustomJob";
import Hero from "../../components/Hero";
import ImageUploader from "../../components/ImageUploader";
import NavBar from "../../components/NavBar";
import { trpc } from "../../utils/trpc";
const NewProduct: NextPage = () => {
  const router = useRouter();
  const productUtil = trpc.useContext();
  const [imageSrc, setImageSrc] = useState();
  const [uploadData, setUploadData] = useState();
  const [isUploading, setIsUploading] = useState(false);
  const [uploadingNewImage, setUploadingNewImage] = useState(false);
  const [imageId, setImageId] = useState("");
  const [selectedCategories, setSelectedCategories] =
    useState<CategoryOption>("Misc");
  const [selectedTags, setSelectedTags] = useState<Array<string>>([]);

  const { data: images } = trpc.product.getImages.useQuery();
  const { data: categories } = trpc.product.getCategories.useQuery();
  const { data: tags } = trpc.product.getTags.useQuery();

  const { mutate, error } = trpc.product.createProduct.useMutation({
    onSuccess: ({ id }) => {
      router.push(`/products/${id}`);
    },
  });
  const { mutate: mutateImage, error: errorImage } =
    trpc.product.createImage.useMutation({
      onSuccess: ({ id }) => {
        productUtil.invalidate();

        setIsUploading(false);
        setImageId(id);
      },
    });

  const handleNameUpdate = (e) => {
    e.preventDefault();

    console.log(e.target.elements["name"].value);
    mutate({
      imageId: imageId,
      name: e.target.elements["name"].value,
      description: e.target.elements["description"].value,
      price: parseFloat(e.target.elements["price"].value),
      tagline: e.target.elements["tagline"].value,
      category: selectedCategories,
      tags: selectedTags,
    });
  };

  const handleImageUpdate = (id: string) => {
    setImageId(id);
  };

  const handleCategoriesUpdate = (id: string) => {
    setSelectedCategories(id as CategoryOption);
  };

  const handleTagsUpdate = (id: string) => {
    if (selectedTags.includes(id))
      setSelectedTags(selectedTags.filter((tag) => tag != id));
    else setSelectedTags([...selectedTags, id]);
  };

  const handleImageUpload = (e) => {
    const reader = new FileReader();

    reader.onload = (onLoadEvt) => {
      setImageSrc(onLoadEvt.target.result);
      setUploadData(undefined);
    };

    reader.readAsDataURL(e.target.files[0]);
  };

  const handleImageSubmit = async (event) => {
    event.preventDefault();
    setIsUploading(true);

    const form = event.currentTarget;
    const fileInput = Array.from(form.elements).find(
      ({ name }) => name === "file"
    );

    const formData = new FormData();

    for (const file of fileInput.files) {
      formData.append("file", file);
    }

    formData.append("upload_preset", "my-uploads");

    const data = await fetch(
      "https://api.cloudinary.com/v1_1/dqeszrzmc/image/upload",
      {
        method: "POST",
        body: formData,
      }
    ).then((r) => r.json());

    setImageSrc(data.secure_url);
    setUploadData(data);
    mutateImage({
      src: data?.secure_url,
    });
  };

  return (
    <>
      <Head>
        <title>Home | DreamWalker Studios</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />

      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
        <h1 className="text-5xl font-extrabold leading-normal text-gray-700 md:text-[5rem]">
          Create a New Product
        </h1>

        <form
          className=" rounded-md p-12 shadow-lg"
          onSubmit={handleNameUpdate}
        >
          <div className="grid grid-cols-6 gap-6">
            <div className="col-span-6 sm:col-span-4">
              <label
                htmlFor="name"
                className="block text-sm font-medium text-gray-700"
              >
                Product Name
              </label>
              <input
                type="text"
                name="name"
                id="name"
                placeholder="Give a unique-ish name for the product"
                className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"
              />
            </div>

            <div className="col-span-6 sm:col-span-2">
              <label
                htmlFor="price"
                className="block text-sm font-medium text-gray-700"
              >
                Price
              </label>
              <input
                type="number"
                name="price"
                step="0.01"
                defaultValue={0.0}
                id="price"
                placeholder="Price pre tax"
                className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"
              />
            </div>

            <div className="col-span-6 sm:col-span-4">
              <label
                htmlFor="description"
                className="block text-sm font-medium text-gray-700"
              >
                Description
              </label>
              <div className="mt-1">
                <textarea
                  id="description"
                  name="description"
                  rows={3}
                  className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"
                  placeholder="Some random description"
                />
              </div>
              <p className="mt-2 text-sm text-gray-500">
                Brief description for the product.
              </p>
            </div>
            <div className="col-span-6 sm:col-span-4">
              <label
                htmlFor="categories"
                className="block text-sm font-medium text-gray-700"
              >
                Categories
              </label>
              <div className="my-2" id="categories">
                {categories &&
                  (
                    Object.keys(categories) as Array<keyof typeof categories>
                  ).map((c) => (
                    <span
                      className={`${
                        selectedCategories.includes(c) &&
                        "border-2 border-gray-800"
                      } mx-2 bg-slate-300 px-2 py-1 font-medium text-white`}
                      key={c}
                      onClick={() => handleCategoriesUpdate(c)}
                    >
                      {c}
                    </span>
                  ))}
              </div>
            </div>

            <div className="col-span-6 sm:col-span-4">
              <label
                htmlFor="tags"
                className="block text-sm font-medium text-gray-700"
              >
                Tags
              </label>
              <div className="my-2" id="tags">
                {tags &&
                  tags.map((t) => (
                    <span
                      className={`${
                        selectedTags.includes(t.id) &&
                        "border-2 border-gray-800"
                      } mx-2 bg-slate-300 px-2 py-1 font-medium text-white`}
                      key={t.id}
                      onClick={() => handleTagsUpdate(t.id)}
                    >
                      {t.name}
                    </span>
                  ))}
              </div>
            </div>

            <div className="col-span-6 sm:col-span-4">
              <label
                htmlFor="tagline"
                className="block text-sm font-medium text-gray-700"
              >
                Tagline
              </label>
              <input
                type="text"
                name="tagline"
                id="tagline"
                placeholder="Some random tagline for homepage"
                className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"
              />
            </div>

            <div className="col-span-6">
              <label
                htmlFor="tagline"
                className="block text-sm font-medium text-gray-700"
              >
                Image Selection
              </label>

              <div className="flex max-w-full flex-row">
                {images &&
                  images.map((image) => (
                    <div
                      className={`${
                        imageId == image.id ? `border-8 border-blue-500` : ""
                      } relative flex h-80 w-80`}
                      key={image.id}
                    >
                      <Image
                        src={image.src}
                        alt={image?.alt ?? ""}
                        layout="fill"
                        onClick={() => handleImageUpdate(image.id)}
                      />
                    </div>
                  ))}
              </div>
            </div>
          </div>

          <button
            type="submit"
            className="my-2 rounded-sm bg-blue-400 p-2 font-medium text-white disabled:cursor-not-allowed disabled:bg-blue-200"
            disabled={isUploading}
          >
            Submit Changes
          </button>
        </form>

        <form
          method="post"
          onChange={handleImageUpload}
          onSubmit={handleImageSubmit}
          className="w-full p-12 shadow-lg"
        >
          <label
            htmlFor="file"
            className="block text-sm font-medium text-gray-700"
          >
            Image Upload to Cloudinary
          </label>

          <input
            type="file"
            name="file"
            id="file"
            placeholder="File"
            className="w-full border-2 p-2"
          />
          <div
            className={`${!imageSrc && "hidden"} relative my-2 flex h-80 w-80`}
          >
            <Image src={imageSrc ?? ""} alt="" layout="fill" />
          </div>
          {isUploading && (
            <button
              type="button"
              className="inline-flex cursor-not-allowed items-center rounded-md bg-indigo-500 px-4 py-2 text-sm font-semibold leading-6 text-white shadow transition duration-150 ease-in-out hover:bg-indigo-400"
              disabled
            >
              <svg
                className="-ml-1 mr-3 h-5 w-5 animate-spin text-white"
                xmlns="http://www.w3.org/2000/svg"
                fill="none"
                viewBox="0 0 24 24"
              >
                <circle
                  className="opacity-25"
                  cx="12"
                  cy="12"
                  r="10"
                  stroke="currentColor"
                  stroke-width="4"
                ></circle>
                <path
                  className="opacity-75"
                  fill="currentColor"
                  d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
                ></path>
              </svg>
              Processing...
            </button>
          )}

          {imageSrc && !uploadData && !isUploading && (
            <p>
              <button className="inline-flex items-center rounded-md bg-indigo-500 px-4 py-2 text-sm font-semibold leading-6 text-white shadow transition duration-150 ease-in-out hover:bg-indigo-400">
                Upload Files
              </button>
            </p>
          )}

          {uploadData && (
            <code>
              <pre>{JSON.stringify(uploadData, null, 2)}</pre>
            </code>
          )}
        </form>

        <AuthShowcase />
      </main>

      <footer className="border-t-2 py-5 text-center">
        <p className="text-sm font-medium">
          ©2022 Made with ❤️ and ☕ by Andrew Hunn
        </p>
      </footer>
    </>
  );
};

export default NewProduct;

const AuthShowcase: React.FC = () => {
  const { data: secretMessage } = trpc.auth.getSecretMessage.useQuery();

  const { data: sessionData } = useSession();

  return (
    <div className="flex flex-col items-center justify-center gap-2">
      {sessionData && (
        <p className="text-2xl text-blue-500">
          Logged in as {sessionData?.user?.name}
        </p>
      )}
      {secretMessage && (
        <p className="text-2xl text-blue-500">{secretMessage}</p>
      )}
      <button
        className="rounded-md border border-black bg-violet-50 px-4 py-2 text-xl shadow-lg hover:bg-violet-100"
        onClick={sessionData ? () => signOut() : () => signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
};
